blank_issues_enabled: false
contact_links:
  - name: Converter Help
    url: https://i.pinimg.com/736x/4f/8f/cd/4f8fcd3d23f48f73a229bdc6bd3a6d0d.jpg
    about: Help with setting up the converter.
  - name: Feature Requests
    url: https://i.pinimg.com/736x/4f/8f/cd/4f8fcd3d23f48f73a229bdc6bd3a6d0d.jpg
    about: Discuss ideas for features to be added to the converter.